### ISSUE TITLE
svg-icon's Features

### ISSUE THREAD

**Issue by edenvidal** [relateapp/svg-icon#3]
- [x] HTML Custom Element (HTMLElement) for SVG icons.
- [x] By default, it fetches icons from /icons, but you can override this by setting the src attribute.
- [x] The default size is 24px, but you can override this by setting the size attribute or with your CSS.
- [x] the icon's fill is the same as the font's inherited color, therefore can be overridden with a class selector.
  - [x] The color attribute can override the icon's fill with plain hex values.

**Comment by edenvidal** [comment]
@farazshah2001

1. Re-2nd checkbox - setting the attribute for `src` in the current implementation is a must. Can we fix this?
2. + Question - Is it possible to develop functionality that overrides the `fill` even though it is set within the .svg?
Thanks!

**Comment by farazshah2001** [comment]
1 - Yes , we can ask the user to set the link to any folder containing svgs as source using 'src' attribute. I will add that functionality.
2 - Yes i believe there must be a method to loop through the inner contents of an svg to overide their fill property. I will look into that as well
